--V1: Criando Tabelas com o Flyway

CREATE TABLE tarefas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(255),
    responsabilidade VARCHAR(255)
);

CREATE TABLE agentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    idade INT,
    Foto_Agente VARCHAR(255),
    Tipo_Agente VARCHAR(255),
    tarefas_id BIGINT,
    CONSTRAINT fk_tarefas FOREIGN KEY (tarefas_id) REFERENCES tarefas(id)
);