--V1: Criando Tabelas com o Flyway

CREATE TABLE tarefas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(255) NOT NULL,
    responsabilidade VARCHAR(100),
    CONSTRAINT tarefas_pk PRIMARY KEY (id)
);

CREATE TABLE agentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    idade INT,
    nivel_de_demanda VARCHAR(100),
    foto_agente VARCHAR(255),
    tipo_agente VARCHAR(255),
    tarefas_id BIGINT,
    CONSTRAINT fk_tarefa FOREIGN KEY (tarefas_id) REFERENCES tarefas(id)
);